import cn from 'classnames';
import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';

import { AppConstants } from '@/app/app.constants';
import Footer from '@/src/components/layout/Footer/Footer';
import Header from '@/src/components/layout/Header/Header';
import Providers from '@/src/components/layout/Providers/Providers';

import './globals.scss';
import styles from './layout.module.scss';

const mainFont = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: {
    template: `%s | ${AppConstants.appName}`,
    default: AppConstants.appName,
  },
  description: 'Generated by create next app',
  keywords: [
    'SmartAce',
    'smart ace',
    'веб разработка',
    'разработка веб приложений',
    'разработка веб сайтов',
    'веб дизайн +и разработка',
    'веб разработка html',
    'мобильная веб разработка',
  ],

  openGraph: {
    ...AppConstants.sharedOpenGraphConfig,

    images: [...(AppConstants.sharedOpenGraphConfig.images ?? [])],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={cn(mainFont.className, styles.appBody)}>
        <Providers>
          <Header />

          {children}

          {/*<Footer />*/}
        </Providers>
      </body>
    </html>
  );
}
